# Generated by Django 3.2.25 on 2024-11-08 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='status',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
    ]
