name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setip Docker-Compose
      run: sudo docker-compose up -d
    - name: Run tests
      run: sudo docker exec backend sh -c "flake8 && pytest ."
