name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  Test:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Install Docker-Compose
      run: |
        sudo apt-get update
        sudo apt-get install -y docker-compose

    - name: Setup Docker-Compose
      run: docker-compose -f docker-compose-stage.yml up -d

    - name: Create migrations
      run: docker-compose exec -T backend sh -c "python manage.py makemigrations"

    - name: Apply migrations
      run: docker-compose exec -T backend sh -c "python manage.py migrate"

    - name: Run Tests
      run: docker-compose exec -T backend sh -c "flake8 . && pytest ."